connectors:
  matrix:
    mxid: "@bot_finglish_to_persian:bot.parsi.ai"
    password: "NLP_HW2_bot"
    rooms:
      main: "#otaghiporazbot7:bot.parsi.ai"
    homeserver: "https://bot.parsi.ai"  # You can omit this if you are using bot.parsi.ai
    nick: "NLP_HW2_7"
    device_id: "OPSDroid"
    enable_encryption: True
skills:
  accept_invite:
    path: skills/accept_invite.py
  hi:
    path: skills/task.py


